pagopa/pagopa-ecommerce-helpdesk-service

- api-spec/openapi.yaml
Add user information into transaction search response
Add user information into transaction search response
> fix: add user informations

- api-spec/openapi.yaml
- src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/EcommerceService.kt
- src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/ResponseBuilder.kt
- src/test/kotlin/it/pagopa/ecommerce/helpdesk/HelpdeskTestUtils.kt
- src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/oracle/PMTransactionDataProviderTest.kt
- Make `paymentDetailInfo` a list inside `paymentInfo` in order to support cart eCommerce transactions (with multiple payment notices)
- Make userInfo as required into response
- Make `paymentDetailInfo` a list inside `paymentInfo` in order to support cart eCommerce transactions (with multiple payment notices)
- Make userInfo as required into response
Local build
> fix(openapi): make payment detail info a list

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- src/main/kotlin/it/pagopa/ecommerce/helpdesk/exceptionhandler/ExceptionHandler.kt
- src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/EcommerceControllerTest.kt
- src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/HelpdeskControllerTest.kt
- src/test/kotlin/it/pagopa/ecommerce/helpdesk/controllers/PmControllerTest.kt
- src/test/kotlin/it/pagopa/ecommerce/helpdesk/exceptionhandler/ExceptionHandlerTest.kt
- Removed error details into ExeptionHandler for generic error replaced with Generic error occurred
- Increase value of initialDelaySeconds for readinessProbe and livenessProbe configuration
The change was made to avoid showing error details to the user
> fix(500) removed error details

- helm/values-prod.yaml
Configure helm values for PROD
Configure helm values for PROD
> chore(helm): prod configuration

- helm/values-prod.yaml
- helm/values-uat.yaml
Increase start delay from 40 to 60s
Increase start delay to avoid reboot loops caused by missing response to liveness due to start up process
> chore(helm): increase start delay for UAT & PROD

- helm/values-prod.yaml
> fix: autoscaling for prod

- helm/values-prod.yaml
Increase initial delay for prod env
Increase initial delay for prod
> fix: increase initial delay for prod

- api-tests/eCommerce-helpdesk.api.tests.dev.json
- api-tests/eCommerce-helpdesk.api.tests.uat.json
Add search dead letter events api tests for DEV and UAT blue/green environments
Add search dead letter events api tests for DEV and UAT blue/green environments
Local collection run
> feat: add api tests for dead letter event search

- src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/oracle/PMPaymentMethodsDataProvider.kt
Fixed statement closure after converting query result to response dto
> CHK-1865 fix: convert into response after statement

- src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/ResponseBuilderV1.kt
Default handling for inconsistent payment method
> CHK-2865 fix: Default handling for inconsistent payment method

- build.gradle.kts
- src/main/kotlin/it/pagopa/ecommerce/helpdesk/SearchParamDecoder.kt
- src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/TransactionDataProvider.kt
- src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/EcommerceTransactionDataProvider.kt
- src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/TransactionsViewRepository.kt
- src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/oracle/PMTransactionDataProvider.kt
- src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/EcommerceService.kt
- src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/HelpdeskService.kt
- src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/PmService.kt
- src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/ConfidentialMailUtils.kt
- src/main/kotlin/it/pagopa/ecommerce/helpdesk/utils/SearchParamDecoder.kt
- src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/EcommerceForTransactionV1DataProviderTest.kt
- src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/mongo/EcommerceForTransactionV2DataProviderTest.kt
- src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/oracle/PMTransactionDataProviderTest.kt
- src/test/kotlin/it/pagopa/ecommerce/helpdesk/exceptionhandler/ExceptionHandlerTest.kt
- src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/EcommerceServiceTest.kt
- src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/HelpdeskServiceTest.kt
- src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/PmServiceTest.kt
Depends on https://github.com/pagopa/pagopa-ecommerce-helpdesk-service/pull/65
Add transaction search by email for eCommerce transactions.
First input email is tokenized with PDV and then search is performed searching by email token.
In order to handle input search criteria transformation (from clear email to PDV token) has been included an input search parameter decoder that, for the moment, takes into account only email transformation tokenizing it and leave all other search parameters intact 
Enable search by user email for eCommerce transactions
Junit tests + local tests using eCommerce dev DB
> feat: add search by email for eCommerce

- helm/values-prod.yaml
Set North Europe explicitly
Set North Europe explicitly
> fix: set north europe explicitly as Mongo host

- helm/values-dev.yaml
Enable search pm in ecommerce history for DEV enviroment
> [PPABV-40] feat: enable search pm in ecommerce history

- api-spec/v1/openapi.yaml
- added paymentEndToEndId field in NpgTransactionInfoDetailsData for the /ecommerce/searchDeadLetterEvents endpoint
> [PPABV-50] feat: add paymentEndToEndId in openapi.yaml

- api-tests/env/helpDesk_dev.env.json
- api-tests/env/helpDesk_local.env.json
- api-tests/env/helpDesk_uat.env.json
- api-tests/env/helpDesk_uat_blue.env.json
- api-tests/v2/eCommerce-helpdesk.api.tests.dev.json
- api-tests/v2/eCommerce-helpdesk.api.tests.local.json
- api-tests/v2/eCommerce-helpdesk.api.tests.uat.json
- docker/pagopa-personal-data-vault-tokenizer/src/db.json
- docker/pagopa-personal-data-vault-tokenizer/src/middleware.js
- added search transaction by user email/fiscal code test APIs to dev collection
- renamed local and dev test APIs to match the existing ones from the UAT collection
- the APIs were missing from the dev collections but present in local and uat ones
- tested with Postman
> [PPABV-42] fix: add missing search transaction test APIs to dev collection

- docker-compose.yml
- docker/npg-mock/Dockerfile.npg-mock
- docker/npg-mock/db.json
- docker/npg-mock/middleware.js
- docker/npg-mock/routes.json
- Add mock NPG on docker-compose
The mock will be used by the application to simulate the getOrder call to NPG.
API local call test
> [PPABV-58] feat: add mock NPG on docker-compose

- helm/values-prod.yaml
Add rollout strategy
Add rollout strategy
> fix: deployment strategy

- api-spec/v1/openapi.yaml
- src/main/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v1/EcommerceController.kt
- src/main/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v1/HelpdeskController.kt
- Move searchNpgOperations API to ecommerce API group
- Add 422 status code response
The API type affects the ecommerce API group and not the helpdesk group.
Postman test call
> [PPABV-57] Edit api path searchNpgOperations

- api-tests/env/helpDesk_uat.env.json
- changed the value of the TRANSACTION_ID_V2 variable
- the variable present is not in the db
> [PPABV-71] fix: changed the value of the uat environment variable

- src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/v1/oracle/PmQueries.kt
- src/test/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/oracle/v1/PmQueriesTest.kt
- added native Oracle SQL queries to be used in the data provider
- the added queries allow transactions searches on the pm based on a date and time range filter
- this was needed to fetch the legacy pm transactions to be imported in the ecommerce-history mongo db
-  to be tested when the mock db is ready
> [PPABV-75] feat: add date filter queries for pm transactions search

- src/main/kotlin/it/pagopa/ecommerce/helpdesk/services/v1/PmService.kt
- src/test/kotlin/it/pagopa/ecommerce/helpdesk/HelpdeskTestUtils.kt
- src/test/kotlin/it/pagopa/ecommerce/helpdesk/services/v1/PmServiceTest.kt
> chore: [bulk transaction] group by id and aggragate payment-info.detail

- api-spec/v1/openapi.yaml
- helm/values-prod.yaml
- refactoring request for bulk API (pm history) according to support Data Factory optimization.
> chore: refactoring request for bulk API (pm history) according to df limitation

- api-spec/v1/openapi.yaml
> revert bulk api

- api-spec/v1/openapi.yaml
- src/main/kotlin/it/pagopa/ecommerce/helpdesk/controllers/v1/EcommerceController.kt
The goal of this PR is to increase page size for deadletter api.
> chore: PIDM-130 increase page size for DL

- api-tests/v1/eCommerce-helpdesk.api.tests.dev.json
- api-tests/v1/eCommerce-helpdesk.api.tests.local.json
- api-tests/v1/eCommerce-helpdesk.api.tests.uat.json
Fix api tests that checks DLQ search api max limit accordingly to the new increased limit 
DLQ search limit where increased in [this pr](https://github.com/pagopa/pagopa-ecommerce-helpdesk-service/pull/181)
> fix: api tests for DLQ over limit

- api-tests/v1/eCommerce-helpdesk.api.tests.uat.json
> fix: [PIDM-133] time range in test

- helm/values-prod.yaml
- helm/values-uat.yaml
Enabled flag to search pm in ecommerce history
> [PIDM-214] chore(ecommerce): enable search pm in ecommerce history

- helm/values-prod.yaml
- helm/values-uat.yaml
- Enable search pm in ecommerce history uat and prod env.
> [PIDM-256] Enable search pm in ecommerce history

- src/main/kotlin/it/pagopa/ecommerce/helpdesk/dataproviders/v2/mongo/EcommerceTransactionDataProvider.kt
Remove search by fiscal code on eCommerce database
Remove search by fiscal code on eCommerce database.
This must be done since query on DB is not tuned up and cause an excessive RU consumption
> chore: disable search by fiscal code

- api-tests/v1/eCommerce-helpdesk.api.tests.uat.json
remove UAT v1 api tests that perform query against dismantled PM DB 
remove UAT v1 api tests that perform query against dismantled PM DB
> chore(api test): remove v1 tests that perform queries against old PM DB
